local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("7lntel x Hub 4.0 ", "DarkTheme")
local Tab = Window:NewTab("MAIN")
local Section = Tab:NewSection("MAIN ALL")
Section:NewButton("วิ่งเร็ว", "วิ่งเร็ว no Bypass", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/pZhkm5mD"))()
end)
Section:NewButton("ทะลุ", "ทะลุทุกอย่าง", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/7Qab6kg9"))()
end)
Section:NewButton("วาป", "วาปไปที่ ที่กด", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/K5FYvtvN"))()
end)
Section:NewButton("หายตัว", "หายตัว", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/3Rnd9rHf"))()
end)
Section:NewLabel("ช่วยเล่น")
Section:NewButton("เสกของ", "เสกของ ได้แค่บางแมพที่ไม่มีการป้องกันเท่านั้น", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub-Backup/main/gametoolgiver.lua"))()
end)
Section:NewButton("ดึงผู้เล่น", "ดึงผู้เล่น ปลอม ทำดาเมจระยะไกลได้", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/5m3k7qv0"))()
end)
Section:NewButton("แมพสว่าง กลางวัน", "จำเป็นในที่มืด", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/fGAgUf87"))()
end)

local Tab = Window:NewTab("ATTACK")
local Section = Tab:NewSection("ATTACK ALL")

Section:NewButton("AIMBOT", "ล็อคหัวผู้เล่น คลิกขวา", function()
    local Aimbot = loadstring(game:HttpGet("https://raw.githubusercontent.com/Exunys/Aimbot-V3/main/src/Aimbot.lua"))()
Aimbot.Load()
end)
Section:NewButton("Hitbox", "hitbox", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/iRyTtfmf"))()
end)
Section:NewButton("KILL BOT ALL", "ฆ่าบอท บางแมพ", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/DczvQZyU"))()
end)

local Tab = Window:NewTab("EPS")
local Section = Tab:NewSection("EPS bot / player ")
Section:NewButton("EPS Player", "มองทะลุผู้เล่น", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/ZkLhNuDL"))()
end)
Section:NewButton("EPS BOT", "มองทะลุ NPC BOT บางแมพ", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/q26QuUBF"))()
end)

local Tab = Window:NewTab("Cmd Admin")
local Section = Tab:NewSection("cmd Admin all ")
Section:NewButton("Infiniteyield", "คำสั่งแอดมิน", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
end)
Section:NewButton("Hack Admin", "บางแมพเท่านั้น ของโหดจริง", function()
    loadstring(game:HttpGet("https://gist.github.com/someunknowndude/38cecea5be9d75cb743eac8b1eaf6758/raw"))()
end)
